version: '3'
services:
  db:
   image: mongo:3.6.12
   ports:
     - "27017:27017"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/
      - HEALTH_CHECK_CACHE=0
    ports:
      - 15672:15672
      - 5672:5672

volumes:
  database: